# This must always remain the same for the Windows installer infrastructure
# to know which program to upgrade.
UPGRADE_GUID = 4fa32a43-31f5-4a7c-b215-db66afcb1816

# The current directory name is "p9term" and ucfirst doesn't look like a good "humanizing" heuristic.
HUMAN_PROJECT_NAME = p9term

include ../../salma-hayek/lib/build/simple.make
