# This must always remain the same for the Windows installer infrastructure
# to know which program to upgrade.
UPGRADE_GUID = f314cb33-6555-49a7-89f6-67bf152493dc

HUMAN_PROJECT_NAME = mp3d

include ../salma-hayek/lib/build/simple.make
