# This must always remain the same for the Windows installer infrastructure
# to know which program to upgrade.
UPGRADE_GUID = 36eea3a0-afb9-420b-b0ac-32650f1c7446

HUMAN_PROJECT_NAME = Mailer

include ../salma-hayek/lib/build/simple.make
