# This must always remain the same for the Windows installer infrastructure
# to know which program to upgrade.
UPGRADE_GUID = f316a738-40a8-402f-b84c-7652847667f6

HUMAN_PROJECT_NAME = LittleHelper

include ../../salma-hayek/lib/build/simple.make
